sudo: false
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 7
  - iojs
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "npm install -g npm@^2"
before_script:
  - npm prune
  - echo "module.exports = require('./config/karma.ci');" > karma.conf.js
install:
  - npm install
script:
  - npm run test
